// CCTech IT Solutions - Central Database v9.0
const CCData = {
  version: "9.0",
  whatsapp: "916364253615",
  
  products: [
    // ==================== COMPUTERS & SERVERS - LATEST MODELS ====================
    // Laptops - 12th/13th/14th Gen
    { id: 1, name: "HP Laptop 15s - i5-1235U, 8GB, 512GB SSD", mainCategory: "Computers & Servers", subCategory: "Laptops", brand: "HP", condition: "NEW", price: 52999, originalPrice: 46086, type: "NEW", image: "images/laptop.png", desc: "Intel 12th Gen i5 • 8GB DDR4 • 512GB NVMe SSD • 15.6\" FHD • Windows 11" },
    { id: 2, name: "Dell Inspiron 15 3520 - i5-1235U, 16GB, 512GB", mainCategory: "Computers & Servers", subCategory: "Laptops", brand: "Dell", condition: "NEW", price: 64999, originalPrice: 56521, type: "NEW", image: "images/laptop.png", desc: "Intel 12th Gen i5 • 16GB DDR4 • 512GB SSD • Backlit Keyboard • FHD Display" },
    { id: 3, name: "Lenovo IdeaPad Slim 3 - i5-12450H, 16GB, 512GB", mainCategory: "Computers & Servers", subCategory: "Laptops", brand: "Lenovo", condition: "NEW", price: 58999, originalPrice: 51303, type: "NEW", image: "images/laptop.png", desc: "Intel 12th Gen i5 • 16GB DDR4 • 512GB SSD • 15.6\" FHD • Thin & Light" },
    { id: 4, name: "HP Pavilion 15 - i7-1255U, 16GB, 512GB SSD", mainCategory: "Computers & Servers", subCategory: "Laptops", brand: "HP", condition: "NEW", price: 74999, originalPrice: 65216, type: "NEW", image: "images/laptop.png", desc: "Intel 12th Gen i7 • 16GB DDR4 • 512GB NVMe • Backlit KB • FHD IPS" },
    { id: 5, name: "Dell Vostro 3520 - i5-1235U, 8GB, 512GB", mainCategory: "Computers & Servers", subCategory: "Laptops", brand: "Dell", condition: "NEW", price: 54999, originalPrice: 47825, type: "NEW", image: "images/laptop.png", desc: "Intel 12th Gen i5 • 8GB DDR4 • 512GB SSD • Business Laptop • Windows 11 Pro" },
    { id: 6, name: "Lenovo ThinkPad E14 Gen 4 - i5-1235U, 8GB, 512GB", mainCategory: "Computers & Servers", subCategory: "Laptops", brand: "Lenovo", condition: "NEW", price: 62999, originalPrice: 54782, type: "NEW", image: "images/laptop.png", desc: "Intel 12th Gen i5 • 8GB DDR4 • 512GB SSD • Fingerprint • 3yr Warranty • Business" },
    { id: 7, name: "HP 15s - Ryzen 5 5500U, 8GB, 512GB", mainCategory: "Computers & Servers", subCategory: "Laptops", brand: "HP", condition: "NEW", price: 44999, originalPrice: 39130, type: "NEW", image: "images/laptop.png", desc: "AMD Ryzen 5 • 8GB DDR4 • 512GB SSD • 15.6\" FHD • Windows 11" },
    { id: 8, name: "Dell Latitude 3420 (REFURBISHED) - i5-1135G7", mainCategory: "Computers & Servers", subCategory: "Laptops", brand: "Dell", condition: "REFURBISHED", price: 34999, originalPrice: 30434, type: "REFURBISHED", image: "images/laptop.png", desc: "Intel 11th Gen i5 • 8GB RAM • 256GB SSD • Grade A • 3 Mo Warranty" },
    { id: 9, name: "HP EliteBook 840 G8 (REFURBISHED) - i5-1135G7", mainCategory: "Computers & Servers", subCategory: "Laptops", brand: "HP", condition: "REFURBISHED", price: 42999, originalPrice: 37391, type: "REFURBISHED", image: "images/laptop.png", desc: "Intel 11th Gen i5 • 8GB RAM • 256GB SSD • FHD • Excellent Condition" },

    // Desktops - 12th/13th/14th Gen
    { id: 10, name: "HP Desktop M01 - i3-12100, 8GB, 256GB SSD", mainCategory: "Computers & Servers", subCategory: "Desktops", brand: "HP", condition: "NEW", price: 34999, originalPrice: 30434, type: "NEW", image: "images/laptop.png", desc: "Intel 12th Gen i3 • 8GB DDR4 • 256GB NVMe SSD • Keyboard + Mouse • Windows 11" },
    { id: 11, name: "Dell Inspiron 3910 - i5-12400, 8GB, 512GB", mainCategory: "Computers & Servers", subCategory: "Desktops", brand: "Dell", condition: "NEW", price: 48999, originalPrice: 42608, type: "NEW", image: "images/laptop.png", desc: "Intel 12th Gen i5 • 8GB DDR4 • 512GB SSD • Tower • Windows 11 Home" },
    { id: 12, name: "Lenovo IdeaCentre 3 - i5-12400, 16GB, 512GB", mainCategory: "Computers & Servers", subCategory: "Desktops", brand: "Lenovo", condition: "NEW", price: 52999, originalPrice: 46086, type: "NEW", image: "images/laptop.png", desc: "Intel 12th Gen i5 • 16GB DDR4 • 512GB SSD • Compact Design • Windows 11" },
    { id: 13, name: "HP ProDesk 400 G9 - i5-12500, 8GB, 1TB", mainCategory: "Computers & Servers", subCategory: "Desktops", brand: "HP", condition: "NEW", price: 54999, originalPrice: 47825, type: "NEW", image: "images/laptop.png", desc: "Intel 12th Gen i5 • 8GB DDR4 • 1TB HDD • Business Desktop • Windows 11 Pro" },
    { id: 14, name: "Dell OptiPlex 3000 - i3-12100, 8GB, 256GB", mainCategory: "Computers & Servers", subCategory: "Desktops", brand: "Dell", condition: "NEW", price: 38999, originalPrice: 33912, type: "NEW", image: "images/laptop.png", desc: "Intel 12th Gen i3 • 8GB DDR4 • 256GB SSD • SFF • Business Ready" },
    { id: 15, name: "Dell OptiPlex 3040 (REFURBISHED) - i5-6500", mainCategory: "Computers & Servers", subCategory: "Desktops", brand: "Dell", condition: "REFURBISHED", price: 22999, originalPrice: 19999, type: "REFURBISHED", image: "images/laptop.png", desc: "Intel 6th Gen i5 • 8GB RAM • 500GB HDD • SFF • Grade A" },

    // Workstations - Latest
    { id: 16, name: "HP Z2 G9 Tower - i7-12700, 32GB, 512GB SSD", mainCategory: "Computers & Servers", subCategory: "Workstations", brand: "HP", condition: "NEW", price: 124999, originalPrice: 108695, type: "NEW", image: "images/laptop.png", desc: "Intel 12th Gen i7 • 32GB DDR4 • 512GB NVMe • Quadro T600 4GB • CAD/3D Ready" },
    { id: 17, name: "Dell Precision 3660 - i7-12700, 32GB, 1TB", mainCategory: "Computers & Servers", subCategory: "Workstations", brand: "Dell", condition: "NEW", price: 134999, originalPrice: 117391, type: "NEW", image: "images/laptop.png", desc: "Intel 12th Gen i7 • 32GB DDR4 • 1TB NVMe • RTX A2000 • Engineering Workstation" },
    { id: 18, name: "Lenovo ThinkStation P360 - i7-12700, 32GB, 512GB", mainCategory: "Computers & Servers", subCategory: "Workstations", brand: "Lenovo", condition: "NEW", price: 129999, originalPrice: 113043, type: "NEW", image: "images/laptop.png", desc: "Intel 12th Gen i7 • 32GB DDR4 • 512GB SSD • Quadro T1000 • Professional" },

    // Servers - Latest
    { id: 19, name: "Dell PowerEdge T150 - Xeon E-2314, 16GB, 2TB", mainCategory: "Computers & Servers", subCategory: "Servers", brand: "Dell", condition: "NEW", price: 114999, originalPrice: 99999, type: "NEW", image: "images/server.png", desc: "Intel Xeon E-2314 • 16GB ECC DDR4 • 2TB HDD • Tower • 3yr Warranty • iDRAC9" },
    { id: 20, name: "HP ProLiant ML350 Gen11 - Xeon Silver 4314, 32GB", mainCategory: "Computers & Servers", subCategory: "Servers", brand: "HP", condition: "NEW", price: 184999, originalPrice: 160869, type: "NEW", image: "images/server.png", desc: "Intel Xeon Silver 4314 • 32GB ECC • 4TB HDD • Tower Server • iLO 6" },
    { id: 21, name: "Dell PowerEdge R250 - Xeon E-2314, 16GB, 1TB", mainCategory: "Computers & Servers", subCategory: "Servers", brand: "Dell", condition: "NEW", price: 124999, originalPrice: 108695, type: "NEW", image: "images/server.png", desc: "Intel Xeon E-2314 • 16GB ECC • 1TB HDD • 1U Rack • iDRAC9 • Entry Server" },
    { id: 22, name: "HP ProLiant DL20 Gen10 Plus - Xeon E-2314, 16GB", mainCategory: "Computers & Servers", subCategory: "Servers", brand: "HP", condition: "NEW", price: 109999, originalPrice: 95652, type: "NEW", image: "images/server.png", desc: "Intel Xeon E-2314 • 16GB ECC • 2x 1TB HDD • 1U Rack • iLO 5" },
    { id: 23, name: "HP ProLiant DL380 G7 (REFURBISHED)", mainCategory: "Computers & Servers", subCategory: "Servers", brand: "HP", condition: "REFURBISHED", price: 74999, originalPrice: 65217, type: "REFURBISHED", image: "images/server.png", desc: "Dual Xeon X5650 • 32GB RAM • 4x 300GB SAS • 2U Rack • Tested" },

    // ==================== CCTV & SECURITY - Latest Models ====================
    { id: 24, name: "Hikvision 2MP Dome Camera DS-2CE56H0T-ITPF", mainCategory: "CCTV & Security", subCategory: "Cameras", brand: "Hikvision", condition: "NEW", price: 2530, originalPrice: 2200, type: "NEW", image: "images/cctv.png", desc: "2MP • 1080p • Dome • IR 20m • Weatherproof • CCTV camera" },
    { id: 25, name: "CP Plus 2MP Bullet Camera CP-VC-B20DLR", mainCategory: "CCTV & Security", subCategory: "Cameras", brand: "CP Plus", condition: "NEW", price: 2185, originalPrice: 1900, type: "NEW", image: "images/cctv.png", desc: "2MP • Bullet • IR 30m • Metal Body • Outdoor • 1080p" },
    { id: 26, name: "Hikvision 4MP Dome Camera DS-2CE76H0T-ITPF", mainCategory: "CCTV & Security", subCategory: "Cameras", brand: "Hikvision", condition: "NEW", price: 3450, originalPrice: 3000, type: "NEW", image: "images/cctv.png", desc: "4MP • 1440p • Dome • IR 20m • ColorVu • Full Color Night" },
    { id: 27, name: "Hikvision 4-Camera 2MP Kit DS-J14A1", mainCategory: "CCTV & Security", subCategory: "DVR/NVR Kits", brand: "Hikvision", condition: "NEW", price: 21275, originalPrice: 18500, type: "NEW", image: "images/cctv.png", desc: "4x 2MP Cameras • 4ch DVR • 1TB HDD • Mobile View • Installation Kit" },
    { id: 28, name: "CP Plus 8-Camera 2MP Kit CP-PLUS-8CH", mainCategory: "CCTV & Security", subCategory: "DVR/NVR Kits", brand: "CP Plus", condition: "NEW", price: 36800, originalPrice: 32000, type: "NEW", image: "images/cctv.png", desc: "8x 2MP Dome • 8ch DVR • 2TB HDD • Night Vision • Mobile App" },
    { id: 29, name: "Hikvision 8MP 4K NVR DS-7608NI-K1/8P", mainCategory: "CCTV & Security", subCategory: "DVR/NVR Kits", brand: "Hikvision", condition: "NEW", price: 17250, originalPrice: 15000, type: "NEW", image: "images/cctv.png", desc: "8ch NVR • 4K Support • 8 PoE Ports • 1 SATA • H.265+" },
    { id: 30, name: "CCTV Power Supply 12V 10A with 10 BNC", mainCategory: "CCTV & Security", subCategory: "Security Accessories", brand: "Generic", condition: "NEW", price: 1725, originalPrice: 1500, type: "NEW", image: "images/cctv.png", desc: "12V 10A PSU • 10x BNC Connectors • CCTV Installation • Surge Protection" },

    // ==================== UPS & POWER BACKUP - Latest Models ====================
    { id: 31, name: "APC Back-UPS 600VA BX600C-IN", mainCategory: "UPS & Power Backup", subCategory: "UPS Units", brand: "APC", condition: "NEW", price: 5175, originalPrice: 4500, type: "NEW", image: "images/accessories.png", desc: "600VA/360W • 4 Outlets • Surge Protection • 2yr Warranty • AVR" },
    { id: 32, name: "Microtek UPS SEBz 1100VA", mainCategory: "UPS & Power Backup", subCategory: "UPS Units", brand: "Microtek", condition: "NEW", price: 3680, originalPrice: 3200, type: "NEW", image: "images/accessories.png", desc: "1100VA • 1 Battery • Pure Sine Wave • LCD Display • 2yr Warranty" },
    { id: 33, name: "Luminous Zelio+ 1100VA Sine Wave", mainCategory: "UPS & Power Backup", subCategory: "UPS Units", brand: "Luminous", condition: "NEW", price: 6670, originalPrice: 5800, type: "NEW", image: "images/accessories.png", desc: "1100VA/900W • Pure Sine Wave • 3yr Warranty • LCD • IT Equipment" },
    { id: 34, name: "APC Smart-UPS 1500VA SMC1500I", mainCategory: "UPS & Power Backup", subCategory: "UPS Units", brand: "APC", condition: "NEW", price: 34500, originalPrice: 30000, type: "NEW", image: "images/accessories.png", desc: "1500VA/1000W • Line Interactive • LCD • USB • 3yr Warranty • Server Grade" },
    { id: 35, name: "Luminous RC18000 Tall Tubular Battery", mainCategory: "UPS & Power Backup", subCategory: "Batteries", brand: "Luminous", condition: "NEW", price: 16675, originalPrice: 14500, type: "NEW", image: "images/accessories.png", desc: "150Ah • Tall Tubular • 60 Months Warranty • Fast Charging • Low Maintenance" },
    { id: 36, name: "Exide Invatubular IT500 Battery", mainCategory: "UPS & Power Backup", subCategory: "Batteries", brand: "Exide", condition: "NEW", price: 15870, originalPrice: 13800, type: "NEW", image: "images/accessories.png", desc: "150Ah • Tubular • 66 Months Warranty • Maintenance Free • Deep Discharge" },
    { id: 37, name: "Amaron Quanta 150Ah Battery", mainCategory: "UPS & Power Backup", subCategory: "Batteries", brand: "Amaron", condition: "NEW", price: 14950, originalPrice: 13000, type: "NEW", image: "images/accessories.png", desc: "150Ah • Tubular • 60 Months Warranty • Silver Alloy • Long Life" },
    { id: 38, name: "V-Guard VG 500 Voltage Stabilizer", mainCategory: "UPS & Power Backup", subCategory: "Stabilizers", brand: "V-Guard", condition: "NEW", price: 3220, originalPrice: 2800, type: "NEW", image: "images/accessories.png", desc: "500VA • AC to DC • TV/Fridge Compatible • 3yr Warranty • LED Indicator" },
    { id: 39, name: "V-Guard Mini Crystal 150 Stabilizer", mainCategory: "UPS & Power Backup", subCategory: "Stabilizers", brand: "V-Guard", condition: "NEW", price: 4025, originalPrice: 3500, type: "NEW", image: "images/accessories.png", desc: "1.5kVA • Wall Mount • LED Display • 3yr Warranty • AC Stabilizer" },

    // ==================== ELECTRONICS & EMBEDDED - Complete Range ====================
    // Development Boards
    { id: 40, name: "Arduino Uno R3 (Original)", mainCategory: "Electronics & Embedded", subCategory: "Development Boards", brand: "Arduino", condition: "NEW", price: 690, originalPrice: 600, type: "BOARD", image: "images/embedded-board.png", desc: "ATmega328P • 16MHz • 14 Digital I/O • 6 Analog • USB • Official" },
    { id: 41, name: "Arduino Nano (Original)", mainCategory: "Electronics & Embedded", subCategory: "Development Boards", brand: "Arduino", condition: "NEW", price: 575, originalPrice: 500, type: "BOARD", image: "images/embedded-board.png", desc: "ATmega328 • Compact • USB Mini • Breadboard Friendly • Official" },
    { id: 42, name: "Arduino Mega 2560 R3", mainCategory: "Electronics & Embedded", subCategory: "Development Boards", brand: "Arduino", condition: "NEW", price: 1265, originalPrice: 1100, type: "BOARD", image: "images/embedded-board.png", desc: "ATmega2560 • 54 Digital I/O • 16 Analog • 256KB Flash • Large Projects" },
    { id: 43, name: "Raspberry Pi 4 Model B 2GB", mainCategory: "Electronics & Embedded", subCategory: "Development Boards", brand: "Raspberry Pi", condition: "NEW", price: 6325, originalPrice: 5500, type: "BOARD", image: "images/embedded-board.png", desc: "Quad-core Cortex-A72 • 2GB RAM • WiFi • BT • GigE • USB 3.0" },
    { id: 44, name: "Raspberry Pi 4 Model B 4GB", mainCategory: "Electronics & Embedded", subCategory: "Development Boards", brand: "Raspberry Pi", condition: "NEW", price: 7590, originalPrice: 6600, type: "BOARD", image: "images/embedded-board.png", desc: "Quad-core Cortex-A72 • 4GB RAM • WiFi • BT • GigE • USB 3.0" },
    { id: 45, name: "Raspberry Pi 4 Model B 8GB", mainCategory: "Electronics & Embedded", subCategory: "Development Boards", brand: "Raspberry Pi", condition: "NEW", price: 10120, originalPrice: 8800, type: "BOARD", image: "images/embedded-board.png", desc: "Quad-core Cortex-A72 • 8GB RAM • WiFi • BT • GigE • Desktop Replacement" },
    { id: 46, name: "Raspberry Pi Zero 2 W", mainCategory: "Electronics & Embedded", subCategory: "Development Boards", brand: "Raspberry Pi", condition: "NEW", price: 1840, originalPrice: 1600, type: "BOARD", image: "images/embedded-board.png", desc: "Quad-core 64-bit • 512MB RAM • WiFi • BT • Compact • IoT Projects" },
    { id: 47, name: "ESP32-WROOM-32D WiFi+BT", mainCategory: "Electronics & Embedded", subCategory: "Development Boards", brand: "Espressif", condition: "NEW", price: 460, originalPrice: 400, type: "MODULE", image: "images/embedded-board.png", desc: "Dual-core • WiFi+Bluetooth • 4MB Flash • IoT Ready • Low Power" },
    { id: 48, name: "ESP8266 NodeMCU V3", mainCategory: "Electronics & Embedded", subCategory: "Development Boards", brand: "Espressif", condition: "NEW", price: 460, originalPrice: 400, type: "MODULE", image: "images/embedded-board.png", desc: "WiFi Module • Lua Firmware • USB-Serial • IoT Projects • Arduino IDE" },
    { id: 49, name: "STM32F103C8T6 Blue Pill", mainCategory: "Electronics & Embedded", subCategory: "Development Boards", brand: "STMicro", condition: "NEW", price: 460, originalPrice: 400, type: "BOARD", image: "images/embedded-board.png", desc: "ARM Cortex-M3 • 72MHz • 64KB Flash • 20KB SRAM • Professional" },

    // Sensors & Modules
    { id: 50, name: "HC-SR04 Ultrasonic Sensor", mainCategory: "Electronics & Embedded", subCategory: "Sensors & Modules", brand: "Generic", condition: "NEW", price: 138, originalPrice: 120, type: "SENSOR", image: "images/sensor.png", desc: "2cm-400cm Range • 5V • Trigger/Echo • Distance Measurement • Arduino" },
    { id: 51, name: "DHT11 Temperature & Humidity", mainCategory: "Electronics & Embedded", subCategory: "Sensors & Modules", brand: "Generic", condition: "NEW", price: 138, originalPrice: 120, type: "SENSOR", image: "images/sensor.png", desc: "20-90% RH • 0-50°C • Digital Output • Low Cost • Weather Station" },
    { id: 52, name: "DHT22 Temperature & Humidity", mainCategory: "Electronics & Embedded", subCategory: "Sensors & Modules", brand: "Generic", condition: "NEW", price: 460, originalPrice: 400, type: "SENSOR", image: "images/sensor.png", desc: "0-100% RH • -40 to 80°C • Higher Accuracy • Digital • Professional" },
    { id: 53, name: "PIR Motion Sensor HC-SR501", mainCategory: "Electronics & Embedded", subCategory: "Sensors & Modules", brand: "Generic", condition: "NEW", price: 196, originalPrice: 170, type: "SENSOR", image: "images/sensor.png", desc: "Infrared Motion • 3-7m Range • Adjustable Delay • 5V • Security" },
    { id: 54, name: "MPU6050 Gyroscope Accelerometer", mainCategory: "Electronics & Embedded", subCategory: "Sensors & Modules", brand: "Generic", condition: "NEW", price: 276, originalPrice: 240, type: "SENSOR", image: "images/sensor.png", desc: "6-Axis • I2C • 3-axis Gyro + 3-axis Accel • Robotics • Drones" },
    { id: 55, name: "BMP180 Barometric Pressure", mainCategory: "Electronics & Embedded", subCategory: "Sensors & Modules", brand: "Generic", condition: "NEW", price: 276, originalPrice: 240, type: "SENSOR", image: "images/sensor.png", desc: "Pressure & Temperature • I2C • 300-1100 hPa • Weather • Altitude" },
    { id: 56, name: "MQ-2 Gas Sensor", mainCategory: "Electronics & Embedded", subCategory: "Sensors & Modules", brand: "Generic", condition: "NEW", price: 196, originalPrice: 170, type: "SENSOR", image: "images/sensor.png", desc: "LPG/Smoke/CO Detection • Analog Output • Heater • Safety • Air Quality" },
    { id: 57, name: "MQ-135 Air Quality Sensor", mainCategory: "Electronics & Embedded", subCategory: "Sensors & Modules", brand: "Generic", condition: "NEW", price: 276, originalPrice: 240, type: "SENSOR", image: "images/sensor.png", desc: "NH3/NOx/Alcohol/Benzene • Air Quality Monitoring • Analog • IoT" },
    { id: 58, name: "Soil Moisture Sensor Capacitive", mainCategory: "Electronics & Embedded", subCategory: "Sensors & Modules", brand: "Generic", condition: "NEW", price: 138, originalPrice: 120, type: "SENSOR", image: "images/sensor.png", desc: "Capacitive • Analog Output • Agriculture • Gardening • Corrosion Resistant" },
    { id: 59, name: "Water Level Sensor", mainCategory: "Electronics & Embedded", subCategory: "Sensors & Modules", brand: "Generic", condition: "NEW", price: 138, originalPrice: 120, type: "SENSOR", image: "images/sensor.png", desc: "8-Level Detection • Analog • Water Tank Monitoring • IoT • Smart Home" },
    { id: 60, name: "Flame Sensor", mainCategory: "Electronics & Embedded", subCategory: "Sensors & Modules", brand: "Generic", condition: "NEW", price: 138, originalPrice: 120, type: "SENSOR", image: "images/sensor.png", desc: "IR Detection • Flame/Fire Detection • Digital/Analog • Safety • Alarm" },
    { id: 61, name: "IR Obstacle Avoidance Sensor", mainCategory: "Electronics & Embedded", subCategory: "Sensors & Modules", brand: "Generic", condition: "NEW", price: 138, originalPrice: 120, type: "SENSOR", image: "images/sensor.png", desc: "IR Reflection • 2-40cm • Robot Obstacle Detection • Arduino • Robotics" },
    { id: 62, name: "IR Remote Control Kit", mainCategory: "Electronics & Embedded", subCategory: "Sensors & Modules", brand: "Generic", condition: "NEW", price: 196, originalPrice: 170, type: "MODULE", image: "images/sensor.png", desc: "38kHz IR • Remote + Receiver • Arduino Compatible • Home Automation" },
    { id: 63, name: "RFID-RC522 Module with Card", mainCategory: "Electronics & Embedded", subCategory: "Sensors & Modules", brand: "Generic", condition: "NEW", price: 345, originalPrice: 300, type: "MODULE", image: "images/sensor.png", desc: "13.56MHz • SPI • Card+Keychain • Access Control • Attendance System" },
    { id: 64, name: "NFC PN532 Module", mainCategory: "Electronics & Embedded", subCategory: "Sensors & Modules", brand: "Generic", condition: "NEW", price: 1035, originalPrice: 900, type: "MODULE", image: "images/sensor.png", desc: "NFC Reader/Writer • I2C/SPI/UART • Mobile Payment • Access Control" },
    { id: 65, name: "GPS NEO-6M Module", mainCategory: "Electronics & Embedded", subCategory: "Sensors & Modules", brand: "Generic", condition: "NEW", price: 748, originalPrice: 650, type: "MODULE", image: "images/sensor.png", desc: "UART • Location Tracking • Antenna Included • Logging • Navigation" },
    { id: 66, name: "Real Time Clock DS3231", mainCategory: "Electronics & Embedded", subCategory: "Sensors & Modules", brand: "Generic", condition: "NEW", price: 276, originalPrice: 240, type: "MODULE", image: "images/sensor.png", desc: "I2C • High Accuracy • Battery Backup • Timekeeping • Data Logging" },
    { id: 67, name: "Relay Module 1-Channel 5V", mainCategory: "Electronics & Embedded", subCategory: "Sensors & Modules", brand: "Generic", condition: "NEW", price: 138, originalPrice: 120, type: "MODULE", image: "images/sensor.png", desc: "10A 250VAC • Optocoupler • Arduino Control • Home Automation • IoT" },
    { id: 68, name: "Relay Module 4-Channel 5V", mainCategory: "Electronics & Embedded", subCategory: "Sensors & Modules", brand: "Generic", condition: "NEW", price: 391, originalPrice: 340, type: "MODULE", image: "images/sensor.png", desc: "4x 10A Relays • Optocoupler • Multi-Device Control • Home Automation" },
    { id: 69, name: "Relay Module 8-Channel 5V", mainCategory: "Electronics & Embedded", subCategory: "Sensors & Modules", brand: "Generic", condition: "NEW", price: 644, originalPrice: 560, type: "MODULE", image: "images/sensor.png", desc: "8x 10A Relays • Optocoupler • Industrial Control • Automation" },

    // Motor Drivers
    { id: 70, name: "L298N Dual H-Bridge Motor Driver", mainCategory: "Electronics & Embedded", subCategory: "Motor Drivers", brand: "Generic", condition: "NEW", price: 230, originalPrice: 200, type: "DRIVER", image: "images/motor-driver.png", desc: "Dual Motor • 2A/Channel • 5-35V • Heat Sink • Robotics • Arduino" },
    { id: 71, name: "L293D Motor Driver Shield", mainCategory: "Electronics & Embedded", subCategory: "Motor Drivers", brand: "Generic", condition: "NEW", price: 265, originalPrice: 230, type: "DRIVER", image: "images/motor-driver.png", desc: "Arduino Shield • 4 Motors • 600mA/Channel • Easy Mount • Robotics" },
    { id: 72, name: "TB6612FNG Dual Motor Driver", mainCategory: "Electronics & Embedded", subCategory: "Motor Drivers", brand: "Generic", condition: "NEW", price: 334, originalPrice: 290, type: "DRIVER", image: "images/motor-driver.png", desc: "Dual Motor • 1.2A/Channel • Efficient • Compact • PWM • Robotics" },
    { id: 73, name: "A4988 Stepper Motor Driver", mainCategory: "Electronics & Embedded", subCategory: "Motor Drivers", brand: "Generic", condition: "NEW", price: 196, originalPrice: 170, type: "DRIVER", image: "images/motor-driver.png", desc: "Stepper Control • Microstepping • 2A • 3D Printers • CNC • Arduino" },
    { id: 74, name: "DRV8825 Stepper Driver", mainCategory: "Electronics & Embedded", subCategory: "Motor Drivers", brand: "Generic", condition: "NEW", price: 265, originalPrice: 230, type: "DRIVER", image: "images/motor-driver.png", desc: "Stepper Control • 1/32 Microstepping • 2.5A • CNC • 3D Printers" },
    { id: 75, name: "ESC 30A Brushless Motor Controller", mainCategory: "Electronics & Embedded", subCategory: "Motor Drivers", brand: "Generic", condition: "NEW", price: 575, originalPrice: 500, type: "DRIVER", image: "images/motor-driver.png", desc: "30A • Brushless Motor • BEC 5V • Drone/RC Applications • Quadcopter" },
    { id: 76, name: "Servo Motor SG90 9g Micro", mainCategory: "Electronics & Embedded", subCategory: "Motor Drivers", brand: "Generic", condition: "NEW", price: 138, originalPrice: 120, type: "MOTOR", image: "images/motor-driver.png", desc: "9g • 1.8kg-cm Torque • 0-180° • Arduino Compatible • Robotics" },
    { id: 77, name: "Servo Motor MG996R High Torque", mainCategory: "Electronics & Embedded", subCategory: "Motor Drivers", brand: "Generic", condition: "NEW", price: 460, originalPrice: 400, type: "MOTOR", image: "images/motor-driver.png", desc: "55g • 10kg-cm Torque • Metal Gear • Robotics • Robot Arm" },
    { id: 78, name: "Stepper Motor NEMA 17", mainCategory: "Electronics & Embedded", subCategory: "Motor Drivers", brand: "Generic", condition: "NEW", price: 518, originalPrice: 450, type: "MOTOR", image: "images/motor-driver.png", desc: "1.8° Step • 1.7A • 40N-cm • 3D Printers • CNC • Precision" },
    { id: 79, name: "DC Gear Motor 12V 100 RPM", mainCategory: "Electronics & Embedded", subCategory: "Motor Drivers", brand: "Generic", condition: "NEW", price: 265, originalPrice: 230, type: "MOTOR", image: "images/motor-driver.png", desc: "12V • 100 RPM • High Torque • Robot Wheels • Automation" },

    // Displays
    { id: 80, name: "16x2 LCD Display HD44780", mainCategory: "Electronics & Embedded", subCategory: "Displays", brand: "Generic", condition: "NEW", price: 265, originalPrice: 230, type: "DISPLAY", image: "images/display.png", desc: "16x2 Characters • HD44780 • Blue Backlight • Parallel • Arduino" },
    { id: 81, name: "16x2 LCD with I2C Interface", mainCategory: "Electronics & Embedded", subCategory: "Displays", brand: "Generic", condition: "NEW", price: 391, originalPrice: 340, type: "DISPLAY", image: "images/display.png", desc: "16x2 • I2C Backpack • 2-Wire Interface • Easy Wiring • Arduino" },
    { id: 82, name: "20x4 LCD Display with I2C", mainCategory: "Electronics & Embedded", subCategory: "Displays", brand: "Generic", condition: "NEW", price: 518, originalPrice: 450, type: "DISPLAY", image: "images/display.png", desc: "20x4 Characters • I2C • More Display Area • Arduino • Projects" },
    { id: 83, name: "OLED 0.96\" I2C 128x64", mainCategory: "Electronics & Embedded", subCategory: "Displays", brand: "Generic", condition: "NEW", price: 334, originalPrice: 290, type: "DISPLAY", image: "images/display.png", desc: "0.96\" • 128x64 Pixels • I2C • White/Blue/Yellow • Low Power" },
    { id: 84, name: "OLED 1.3\" I2C 128x64", mainCategory: "Electronics & Embedded", subCategory: "Displays", brand: "Generic", condition: "NEW", price: 460, originalPrice: 400, type: "DISPLAY", image: "images/display.png", desc: "1.3\" • 128x64 • I2C • Larger Display • White/Blue • Arduino" },
    { id: 85, name: "TFT 2.4\" Touch Screen Shield", mainCategory: "Electronics & Embedded", subCategory: "Displays", brand: "Generic", condition: "NEW", price: 713, originalPrice: 620, type: "DISPLAY", image: "images/display.png", desc: "2.4\" • 240x320 • Touch • Arduino Shield • SD Card • Graphics" },
    { id: 86, name: "TFT 2.8\" Touch Screen", mainCategory: "Electronics & Embedded", subCategory: "Displays", brand: "Generic", condition: "NEW", price: 897, originalPrice: 780, type: "DISPLAY", image: "images/display.png", desc: "2.8\" • 240x320 • Resistive Touch • SPI Interface • Arduino" },
    { id: 87, name: "Nextion 2.4\" HMI Display", mainCategory: "Electronics & Embedded", subCategory: "Displays", brand: "Generic", condition: "NEW", price: 2530, originalPrice: 2200, type: "DISPLAY", image: "images/display.png", desc: "2.4\" • Touch • UART • GUI Builder • Professional HMI • Industrial" },
    { id: 88, name: "LED Matrix 8x8 MAX7219", mainCategory: "Electronics & Embedded", subCategory: "Displays", brand: "Generic", condition: "NEW", price: 196, originalPrice: 170, type: "DISPLAY", image: "images/display.png", desc: "8x8 LED • MAX7219 Driver • SPI • Daisy-Chainable • Scrolling Text" },
    { id: 89, name: "7-Segment Display 4-Digit", mainCategory: "Electronics & Embedded", subCategory: "Displays", brand: "Generic", condition: "NEW", price: 138, originalPrice: 120, type: "DISPLAY", image: "images/display.png", desc: "4-Digit • Common Cathode • Time Display • Counter • Arduino" },

    // Power Supplies
    { id: 90, name: "Breadboard Power Supply 5V/3.3V", mainCategory: "Electronics & Embedded", subCategory: "Power Supplies", brand: "Generic", condition: "NEW", price: 196, originalPrice: 170, type: "POWER", image: "images/power-supply.png", desc: "Dual Voltage • Breadboard Compatible • USB/DC Input • Arduino" },
    { id: 91, name: "LM2596 DC-DC Buck Converter", mainCategory: "Electronics & Embedded", subCategory: "Power Supplies", brand: "Generic", condition: "NEW", price: 138, originalPrice: 120, type: "POWER", image: "images/power-supply.png", desc: "Step-Down • 3A • 4-40V to 1.25-37V • Adjustable • Efficient" },
    { id: 92, name: "MT3608 DC-DC Boost Converter", mainCategory: "Electronics & Embedded", subCategory: "Power Supplies", brand: "Generic", condition: "NEW", price: 138, originalPrice: 120, type: "POWER", image: "images/power-supply.png", desc: "Step-Up • 2A • 2-24V Input • Compact • Efficient • Arduino" },
    { id: 93, name: "USB Power Bank Module 5V 2A", mainCategory: "Electronics & Embedded", subCategory: "Power Supplies", brand: "Generic", condition: "NEW", price: 265, originalPrice: 230, type: "POWER", image: "images/power-supply.png", desc: "18650 Battery Holder • 5V 2A Output • Charging Circuit • DIY Power Bank" },
    { id: 94, name: "TP4056 Li-ion Battery Charger", mainCategory: "Electronics & Embedded", subCategory: "Power Supplies", brand: "Generic", condition: "NEW", price: 69, originalPrice: 60, type: "POWER", image: "images/power-supply.png", desc: "1A Charging • Micro USB • Protection • 18650 Compatible • DIY" },
    { id: 95, name: "18650 Li-ion Battery 3.7V 2600mAh", mainCategory: "Electronics & Embedded", subCategory: "Power Supplies", brand: "Generic", condition: "NEW", price: 265, originalPrice: 230, type: "BATTERY", image: "images/power-supply.png", desc: "3.7V • 2600mAh • Rechargeable • Protected • DIY Projects" },
    { id: 96, name: "9V Battery Snap Connector", mainCategory: "Electronics & Embedded", subCategory: "Power Supplies", brand: "Generic", condition: "NEW", price: 28, originalPrice: 24, type: "ACCESSORY", image: "images/power-supply.png", desc: "9V Battery Clip • Snap Connector • Arduino Projects • DIY" },
    { id: 97, name: "DC Power Jack 5.5mm x 2.1mm", mainCategory: "Electronics & Embedded", subCategory: "Power Supplies", brand: "Generic", condition: "NEW", price: 28, originalPrice: 24, type: "CONNECTOR", image: "images/power-supply.png", desc: "DC Jack • 5.5x2.1mm • PCB Mount • Power Input • Arduino" },

    // Components
    { id: 98, name: "Breadboard 830 Tie-Points", mainCategory: "Electronics & Embedded", subCategory: "Components", brand: "Generic", condition: "NEW", price: 138, originalPrice: 120, type: "COMPONENT", image: "images/components.png", desc: "830 Holes • Solderless • Adhesive Backing • Power Rails • Prototyping" },
    { id: 99, name: "Mini Breadboard 400 Points", mainCategory: "Electronics & Embedded", subCategory: "Components", brand: "Generic", condition: "NEW", price: 69, originalPrice: 60, type: "COMPONENT", image: "images/components.png", desc: "400 Holes • Compact • Portable • Prototyping • Arduino" },
    { id: 100, name: "Jumper Wires M-M 120pcs", mainCategory: "Electronics & Embedded", subCategory: "Components", brand: "Generic", condition: "NEW", price: 196, originalPrice: 170, type: "COMPONENT", image: "images/components.png", desc: "Male-to-Male • 20cm • 120 Pieces • Assorted Colors • Breadboard" },
    { id: 101, name: "Jumper Wires M-F 120pcs", mainCategory: "Electronics & Embedded", subCategory: "Components", brand: "Generic", condition: "NEW", price: 196, originalPrice: 170, type: "COMPONENT", image: "images/components.png", desc: "Male-to-Female • 20cm • 120 Pieces • Breadboard to Module" },
    { id: 102, name: "Jumper Wires F-F 120pcs", mainCategory: "Electronics & Embedded", subCategory: "Components", brand: "Generic", condition: "NEW", price: 196, originalPrice: 170, type: "COMPONENT", image: "images/components.png", desc: "Female-to-Female • 20cm • 120 Pieces • Module to Module" },
    { id: 103, name: "Resistor Kit 1/4W 600pcs", mainCategory: "Electronics & Embedded", subCategory: "Components", brand: "Generic", condition: "NEW", price: 334, originalPrice: 290, type: "COMPONENT", image: "images/components.png", desc: "10Ω-1MΩ • 30 Values • 5% Tolerance • Storage Box • Arduino" },
    { id: 104, name: "Capacitor Kit 240pcs", mainCategory: "Electronics & Embedded", subCategory: "Components", brand: "Generic", condition: "NEW", price: 391, originalPrice: 340, type: "COMPONENT", image: "images/components.png", desc: "Ceramic & Electrolytic • 12 Values • 0.1uF-100uF • Electronics" },
    { id: 105, name: "LED Kit 5mm 200pcs", mainCategory: "Electronics & Embedded", subCategory: "Components", brand: "Generic", condition: "NEW", price: 196, originalPrice: 170, type: "COMPONENT", image: "images/components.png", desc: "Red/Green/Blue/Yellow/White • 40pcs Each • 3-5V • Arduino" },
    { id: 106, name: "Push Button Tactile 100pcs", mainCategory: "Electronics & Embedded", subCategory: "Components", brand: "Generic", condition: "NEW", price: 138, originalPrice: 120, type: "COMPONENT", image: "images/components.png", desc: "12x12x7mm • 6-Pin • Through-Hole • Momentary • Arduino" },
    { id: 107, name: "Slide Switch SPDT 50pcs", mainCategory: "Electronics & Embedded", subCategory: "Components", brand: "Generic", condition: "NEW", price: 138, originalPrice: 120, type: "COMPONENT", image: "images/components.png", desc: "SPDT • 3-Pin • Through-Hole • ON/OFF Switch • Arduino" },
    { id: 108, name: "Potentiometer 10K 10pcs", mainCategory: "Electronics & Embedded", subCategory: "Components", brand: "Generic", condition: "NEW", price: 138, originalPrice: 120, type: "COMPONENT", image: "images/components.png", desc: "10KΩ • Rotary • Variable Resistor • Analog Input • Arduino" },
    { id: 109, name: "LM7805 5V Voltage Regulator", mainCategory: "Electronics & Embedded", subCategory: "Components", brand: "Generic", condition: "NEW", price: 16, originalPrice: 14, type: "COMPONENT", image: "images/components.png", desc: "5V Output • 1.5A • TO-220 • Thermal Protection • Power Supply" },
    { id: 110, name: "LM7812 12V Voltage Regulator", mainCategory: "Electronics & Embedded", subCategory: "Components", brand: "Generic", condition: "NEW", price: 16, originalPrice: 14, type: "COMPONENT", image: "images/components.png", desc: "12V Output • 1.5A • TO-220 • Linear Regulator • Power Supply" },
    { id: 111, name: "NE555 Timer IC 10pcs", mainCategory: "Electronics & Embedded", subCategory: "Components", brand: "Generic", condition: "NEW", price: 69, originalPrice: 60, type: "COMPONENT", image: "images/components.png", desc: "Timer IC • DIP-8 • Oscillator • Pulse Generation • Electronics" },
    { id: 112, name: "LM358 Dual Op-Amp 10pcs", mainCategory: "Electronics & Embedded", subCategory: "Components", brand: "Generic", condition: "NEW", price: 69, originalPrice: 60, type: "COMPONENT", image: "images/components.png", desc: "Dual Op-Amp • DIP-8 • Low Power • Signal Conditioning • Audio" },
    { id: 113, name: "Diode 1N4007 100pcs", mainCategory: "Electronics & Embedded", subCategory: "Components", brand: "Generic", condition: "NEW", price: 69, originalPrice: 60, type: "COMPONENT", image: "images/components.png", desc: "1A 1000V • Rectifier • Through-Hole • General Purpose • Power" },
    { id: 114, name: "Zener Diode Kit 50pcs", mainCategory: "Electronics & Embedded", subCategory: "Components", brand: "Generic", condition: "NEW", price: 138, originalPrice: 120, type: "COMPONENT", image: "images/components.png", desc: "3.3V-24V • 10 Values • Voltage Regulation • Protection • Electronics" },
    { id: 115, name: "Transistor BC547 100pcs", mainCategory: "Electronics & Embedded", subCategory: "Components", brand: "Generic", condition: "NEW", price: 69, originalPrice: 60, type: "COMPONENT", image: "images/components.png", desc: "NPN • 45V 100mA • TO-92 • General Purpose • Amplifier • Switch" },
    { id: 116, name: "MOSFET IRF540N 10pcs", mainCategory: "Electronics & Embedded", subCategory: "Components", brand: "Generic", condition: "NEW", price: 138, originalPrice: 120, type: "COMPONENT", image: "images/components.png", desc: "N-Channel • 100V 33A • TO-220 • Switching • Motor Control" },
    { id: 117, name: "Crystal Oscillator 16MHz 10pcs", mainCategory: "Electronics & Embedded", subCategory: "Components", brand: "Generic", condition: "NEW", price: 69, originalPrice: 60, type: "COMPONENT", image: "images/components.png", desc: "16MHz • HC-49S • Arduino • Microcontroller Clock • Timing" },

    // Enclosures
    { id: 118, name: "CircuitX PES01 Plastic Box Small", mainCategory: "Electronics & Embedded", subCategory: "Enclosures", brand: "Generic", condition: "NEW", price: 69, originalPrice: 60, type: "ENCLOSURE", image: "images/enclosure.png", desc: "95x65x35mm • ABS Plastic • Screw Holes • PCB Mounting • Projects" },
    { id: 119, name: "CircuitX PES02 Plastic Box Medium", mainCategory: "Electronics & Embedded", subCategory: "Enclosures", brand: "Generic", condition: "NEW", price: 138, originalPrice: 120, type: "ENCLOSURE", image: "images/enclosure.png", desc: "115x90x55mm • ABS Plastic • Durable • Project Box • Electronics" },
    { id: 120, name: "CircuitX PES03 Plastic Box Large", mainCategory: "Electronics & Embedded", subCategory: "Enclosures", brand: "Generic", condition: "NEW", price: 196, originalPrice: 170, type: "ENCLOSURE", image: "images/enclosure.png", desc: "158x108x62mm • ABS Plastic • Spacious • Electronics • Projects" },
    { id: 121, name: "Aluminum Enclosure Box Small", mainCategory: "Electronics & Embedded", subCategory: "Enclosures", brand: "Generic", condition: "NEW", price: 460, originalPrice: 400, type: "ENCLOSURE", image: "images/enclosure.png", desc: "115x90x55mm • Die-Cast Aluminum • IP54 • EMI Shielding • Professional" },
    { id: 122, name: "Aluminum Enclosure Box Medium", mainCategory: "Electronics & Embedded", subCategory: "Enclosures", brand: "Generic", condition: "NEW", price: 644, originalPrice: 560, type: "ENCLOSURE", image: "images/enclosure.png", desc: "158x108x62mm • Aluminum • Heat Dissipation • Professional • Industrial" },
    { id: 123, name: "Raspberry Pi 4 Case with Fan", mainCategory: "Electronics & Embedded", subCategory: "Enclosures", brand: "Generic", condition: "NEW", price: 575, originalPrice: 500, type: "ENCLOSURE", image: "images/enclosure.png", desc: "Dual Fan • Heat Sinks • Easy Access • ABS • Black/Red • Cooling" },
    { id: 124, name: "Arduino Uno Case", mainCategory: "Electronics & Embedded", subCategory: "Enclosures", brand: "Generic", condition: "NEW", price: 265, originalPrice: 230, type: "ENCLOSURE", image: "images/enclosure.png", desc: "Acrylic • Laser Cut • Screw Assembly • Protection • Arduino Uno" },
    { id: 125, name: "Waterproof Junction Box IP65", mainCategory: "Electronics & Embedded", subCategory: "Enclosures", brand: "Generic", condition: "NEW", price: 518, originalPrice: 450, type: "ENCLOSURE", image: "images/enclosure.png", desc: "190x140x70mm • IP65 • Outdoor • Cable Glands • Weatherproof" },
    { id: 126, name: "DIN Rail Mount Enclosure", mainCategory: "Electronics & Embedded", subCategory: "Enclosures", brand: "Generic", condition: "NEW", price: 644, originalPrice: 560, type: "ENCLOSURE", image: "images/enclosure.png", desc: "DIN Rail • Industrial • PLC Mounting • Modular • Automation" },
    { id: 127, name: "Project Box with Transparent Lid", mainCategory: "Electronics & Embedded", subCategory: "Enclosures", brand: "Generic", condition: "NEW", price: 334, originalPrice: 290, type: "ENCLOSURE", image: "images/enclosure.png", desc: "150x100x50mm • Clear Lid • ABS • LED Visible • Projects" },

    // Tools & Equipment
    { id: 128, name: "Digital Multimeter DT830D", mainCategory: "Electronics & Embedded", subCategory: "Tools & Equipment", brand: "Generic", condition: "NEW", price: 311, originalPrice: 270, type: "TOOL", image: "images/tools.png", desc: "DC/AC Voltage • Current • Resistance • Diode • Buzzer • Testing" },
    { id: 129, name: "Soldering Iron 60W Adjustable", mainCategory: "Electronics & Embedded", subCategory: "Tools & Equipment", brand: "Generic", condition: "NEW", price: 713, originalPrice: 620, type: "TOOL", image: "images/tools.png", desc: "200-450°C • Temperature Control • 5 Tips • Stand • ON/OFF • Soldering" },
    { id: 130, name: "Soldering Station 936 60W", mainCategory: "Electronics & Embedded", subCategory: "Tools & Equipment", brand: "Generic", condition: "NEW", price: 1898, originalPrice: 1650, type: "TOOL", image: "images/tools.png", desc: "Temperature Controlled • Digital Display • ESD Safe • Professional" },
    { id: 131, name: "Solder Wire 0.8mm 100g", mainCategory: "Electronics & Embedded", subCategory: "Tools & Equipment", brand: "Generic", condition: "NEW", price: 391, originalPrice: 340, type: "TOOL", image: "images/tools.png", desc: "60/40 Tin/Lead • Rosin Core • 0.8mm • 100g Spool • Soldering" },
    { id: 132, name: "Solder Wire Lead-Free 0.8mm", mainCategory: "Electronics & Embedded", subCategory: "Tools & Equipment", brand: "Generic", condition: "NEW", price: 518, originalPrice: 450, type: "TOOL", image: "images/tools.png", desc: "Lead-Free • 0.8mm • RoHS Compliant • 100g • Eco-Friendly" },
    { id: 133, name: "Desoldering Pump Solder Sucker", mainCategory: "Electronics & Embedded", subCategory: "Tools & Equipment", brand: "Generic", condition: "NEW", price: 196, originalPrice: 170, type: "TOOL", image: "images/tools.png", desc: "Spring-Loaded • Aluminum • Heat-Resistant • PCB Repair • Desoldering" },
    { id: 134, name: "Desoldering Braid Wick", mainCategory: "Electronics & Embedded", subCategory: "Tools & Equipment", brand: "Generic", condition: "NEW", price: 138, originalPrice: 120, type: "TOOL", image: "images/tools.png", desc: "2.5mm x 1.5m • Copper Braid • Flux Coated • Solder Removal • PCB" },
    { id: 135, name: "Helping Hands with Magnifier", mainCategory: "Electronics & Embedded", subCategory: "Tools & Equipment", brand: "Generic", condition: "NEW", price: 460, originalPrice: 400, type: "TOOL", image: "images/tools.png", desc: "Adjustable Arms • Magnifying Glass • LED Light • Soldering • PCB Work" },
    { id: 136, name: "Wire Stripper Tool", mainCategory: "Electronics & Embedded", subCategory: "Tools & Equipment", brand: "Generic", condition: "NEW", price: 334, originalPrice: 290, type: "TOOL", image: "images/tools.png", desc: "Automatic • 10-24 AWG • Strip/Crimp/Cut • Multi-Function • Electrician" },
    { id: 137, name: "Precision Screwdriver Set 32pcs", mainCategory: "Electronics & Embedded", subCategory: "Tools & Equipment", brand: "Generic", condition: "NEW", price: 575, originalPrice: 500, type: "TOOL", image: "images/tools.png", desc: "32 Bits • Phillips/Flathead/Torx • Electronics Repair • Laptop • Phone" },
    { id: 138, name: "Tweezers Set 5pcs", mainCategory: "Electronics & Embedded", subCategory: "Tools & Equipment", brand: "Generic", condition: "NEW", price: 196, originalPrice: 170, type: "TOOL", image: "images/tools.png", desc: "Stainless Steel • Anti-Static • Curved/Straight • SMD • Precision Work" },
    { id: 139, name: "PCB Holder Vise", mainCategory: "Electronics & Embedded", subCategory: "Tools & Equipment", brand: "Generic", condition: "NEW", price: 644, originalPrice: 560, type: "TOOL", image: "images/tools.png", desc: "Adjustable • Helping Hands • PCB Soldering • Stable • Electronics Work" },
    { id: 140, name: "Hot Air Rework Station", mainCategory: "Electronics & Embedded", subCategory: "Tools & Equipment", brand: "Generic", condition: "NEW", price: 3795, originalPrice: 3300, type: "TOOL", image: "images/tools.png", desc: "SMD/SMT • Temperature Control • Air Flow • Desoldering • Professional" },
    { id: 141, name: "USB Logic Analyzer 8-Channel", mainCategory: "Electronics & Embedded", subCategory: "Tools & Equipment", brand: "Generic", condition: "NEW", price: 575, originalPrice: 500, type: "TOOL", image: "images/tools.png", desc: "24MHz • 8-Channel • USB • Protocol Debugging • I2C/SPI/UART" },
    { id: 142, name: "Oscilloscope Probe Set", mainCategory: "Electronics & Embedded", subCategory: "Tools & Equipment", brand: "Generic", condition: "NEW", price: 644, originalPrice: 560, type: "TOOL", image: "images/tools.png", desc: "100MHz • 1X/10X • BNC • Signal Measurement • Testing • Debugging" },

    // Robotics Kits
    { id: 143, name: "Arduino Robot Car Chassis Kit", mainCategory: "Electronics & Embedded", subCategory: "Robotics Kits", brand: "Generic", condition: "NEW", price: 1898, originalPrice: 1650, type: "KIT", image: "images/robotics.png", desc: "2WD • Acrylic Chassis • Motors • Wheels • Ultrasonic Sensor • Arduino" },
    { id: 144, name: "4WD Robot Car Chassis", mainCategory: "Electronics & Embedded", subCategory: "Robotics Kits", brand: "Generic", condition: "NEW", price: 2530, originalPrice: 2200, type: "KIT", image: "images/robotics.png", desc: "4-Wheel Drive • Metal Chassis • High Torque • Obstacle Avoid • Arduino" },
    { id: 145, name: "Hexapod Robot Spider Kit", mainCategory: "Electronics & Embedded", subCategory: "Robotics Kits", brand: "Generic", condition: "NEW", price: 3795, originalPrice: 3300, type: "KIT", image: "images/robotics.png", desc: "6-Leg • 18 Servos • Arduino Control • Walking Robot • Advanced" },
    { id: 146, name: "Robot Arm Kit 6-DOF", mainCategory: "Electronics & Embedded", subCategory: "Robotics Kits", brand: "Generic", condition: "NEW", price: 5060, originalPrice: 4400, type: "KIT", image: "images/robotics.png", desc: "6 Degrees • Metal • Servos • Gripper • Arduino • Pick & Place" },
    { id: 147, name: "Line Follower Sensor Array", mainCategory: "Electronics & Embedded", subCategory: "Robotics Kits", brand: "Generic", condition: "NEW", price: 334, originalPrice: 290, type: "SENSOR", image: "images/robotics.png", desc: "8-Channel • IR Sensors • Line Tracking • Robot Navigation • Arduino" },
    { id: 148, name: "Wheel Encoder DC Motor", mainCategory: "Electronics & Embedded", subCategory: "Robotics Kits", brand: "Generic", condition: "NEW", price: 518, originalPrice: 450, type: "MOTOR", image: "images/robotics.png", desc: "With Encoder • 12V • 210 RPM • Precise Control • Robotics • Arduino" },
    { id: 149, name: "Omni Wheel 60mm", mainCategory: "Electronics & Embedded", subCategory: "Robotics Kits", brand: "Generic", condition: "NEW", price: 265, originalPrice: 230, type: "WHEEL", image: "images/robotics.png", desc: "60mm • 3-Roller • Mecanum • Omni-Directional Movement • Robotics" },
    { id: 150, name: "Robot Caster Wheel", mainCategory: "Electronics & Embedded", subCategory: "Robotics Kits", brand: "Generic", condition: "NEW", price: 138, originalPrice: 120, type: "WHEEL", image: "images/robotics.png", desc: "Free Rotating • Support Wheel • Robot Balance • Arduino • DIY" },

    // ==================== ACCESSORIES & SPARE PARTS ====================
    { id: 151, name: "Samsung 970 EVO Plus 1TB NVMe", mainCategory: "Accessories & Spare Parts", subCategory: "Storage", brand: "Samsung", condition: "NEW", price: 7475, originalPrice: 6500, type: "STORAGE", image: "images/accessories.png", desc: "Read: 3500MB/s • Write: 3300MB/s • 5yr Warranty • NVMe • Fast" },
    { id: 152, name: "Corsair Vengeance 16GB DDR4 3200MHz", mainCategory: "Accessories & Spare Parts", subCategory: "RAM", brand: "Corsair", condition: "NEW", price: 3795, originalPrice: 3300, type: "RAM", image: "images/accessories.png", desc: "3200MHz • CL16 • Desktop • Lifetime Warranty • Gaming • RGB" },
    { id: 153, name: "LG 24\" IPS Monitor FHD 75Hz", mainCategory: "Accessories & Spare Parts", subCategory: "Monitors", brand: "LG", condition: "NEW", price: 11499, originalPrice: 9999, type: "MONITOR", image: "images/accessories.png", desc: "1920x1080 • IPS Panel • HDMI + VGA • Eye Care • 3yr • 75Hz" },
    { id: 154, name: "Logitech Wireless Keyboard & Mouse", mainCategory: "Accessories & Spare Parts", subCategory: "Peripherals", brand: "Logitech", condition: "NEW", price: 1725, originalPrice: 1500, type: "ACCESSORY", image: "images/accessories.png", desc: "2.4GHz Wireless • 10m Range • Long Battery • Spill Resistant • Combo" },
    { id: 155, name: "HDMI Cable 2.0 3m", mainCategory: "Accessories & Spare Parts", subCategory: "Cables & Adapters", brand: "Generic", condition: "NEW", price: 403, originalPrice: 350, type: "CABLE", image: "images/accessories.png", desc: "HDMI 2.0 • 4K@60Hz • 3 Meter • Gold Plated • High Speed" },
    { id: 156, name: "USB 3.0 Extension Cable 3m", mainCategory: "Accessories & Spare Parts", subCategory: "Cables & Adapters", brand: "Generic", condition: "NEW", price: 288, originalPrice: 250, type: "CABLE", image: "images/accessories.png", desc: "USB 3.0 • 3 Meter • Male to Female • High Speed • Extension" },
    { id: 157, name: "Webcam HD 1080p with Mic", mainCategory: "Accessories & Spare Parts", subCategory: "Peripherals", brand: "Generic", condition: "NEW", price: 2185, originalPrice: 1900, type: "ACCESSORY", image: "images/accessories.png", desc: "1080p Full HD • Built-in Mic • USB • Auto Focus • Video Calls" },
    { id: 158, name: "External HDD 1TB USB 3.0", mainCategory: "Accessories & Spare Parts", subCategory: "Storage", brand: "WD", condition: "NEW", price: 4599, originalPrice: 3999, type: "STORAGE", image: "images/accessories.png", desc: "1TB • USB 3.0 • Portable • Plug & Play • Backup • WD" },
    { id: 159, name: "Dell 24\" Monitor (REFURBISHED)", mainCategory: "Accessories & Spare Parts", subCategory: "Monitors", brand: "Dell", condition: "REFURBISHED", price: 7475, originalPrice: 6500, type: "REFURBISHED", image: "images/accessories.png", desc: "24\" FHD • IPS • HDMI/VGA • Grade A • 3 Mo Warranty • Dell" },
    { id: 160, name: "HP 65W Laptop Adapter (REFURBISHED)", mainCategory: "Accessories & Spare Parts", subCategory: "Cables & Adapters", brand: "HP", condition: "REFURBISHED", price: 920, originalPrice: 800, type: "REFURBISHED", image: "images/accessories.png", desc: "19.5V 3.34A • Tested • Working Condition • Multiple Tips • HP" }
  ],

  services: [
    { id: 101, name: "Windows 11 Clean Installation", category: "OS Installation", price: 1500, image: "images/service-os.png", desc: "Full Backup • Fresh Install • All Drivers • Optimization" },
    { id: 102, name: "Virus & Malware Removal", category: "Virus Removal", price: 1200, image: "images/service-virus.png", desc: "Deep Scan • Quarantine • Cleanup • Antivirus Setup" },
    { id: 103, name: "Laptop Display Replacement", category: "Display & Hardware Fix", price: 3500, image: "images/service-hardware.png", desc: "Cracked/Broken Screen • Genuine Panels • 30min-1hr (Panel Extra)" },
    { id: 104, name: "Data Recovery HDD/SSD", category: "Data Recovery", price: 3000, image: "images/service-data-recovery.png", desc: "Deleted Files • Formatted Drive • Corrupted Data • Professional" },
    { id: 105, name: "Home/Office Network Setup", category: "Networking Setup", price: 2500, image: "images/service-network.png", desc: "Router Config • WiFi Setup • Printer Sharing • Security" },
    { id: 106, name: "Annual Maintenance Contract AMC", category: "AMC Plans", price: 5000, image: "images/service-amc.png", desc: "Quarterly Visits • Priority Support • Updates • 1 Year" },
    { id: 107, name: "Laptop Motherboard Repair", category: "Hardware Repair", price: 2500, image: "images/service-hardware.png", desc: "Chip-Level Repair • Power Issue • No Display • Component Replacement" },
    { id: 108, name: "Desktop Motherboard Repair", category: "Hardware Repair", price: 2000, image: "images/service-hardware.png", desc: "Chip-Level Repair • Power Issue • No Boot • Component Replacement" },
    { id: 109, name: "Server Hardware Repair", category: "Hardware Repair", price: 5000, image: "images/service-hardware.png", desc: "Server Motherboard • RAID Controller • PSU • HDD/SSD Replacement" },
    { id: 110, name: "Workstation Repair", category: "Hardware Repair", price: 3500, image: "images/service-hardware.png", desc: "Workstation Motherboard • GPU • RAM • Professional Repair" },
    { id: 111, name: "Laptop Keyboard Replacement", category: "Hardware Repair", price: 1500, image: "images/service-hardware.png", desc: "All Brands • Original/OEM • Backlit Option • Quick Service" },
    { id: 112, name: "Laptop Battery Replacement", category: "Hardware Repair", price: 1000, image: "images/service-hardware.png", desc: "All Models • Original/OEM • 6-8 Hours Backup • Warranty" },
    { id: 113, name: "Laptop Screen Replacement", category: "Display & Hardware Fix", price: 3500, image: "images/service-hardware.png", desc: "All Sizes • FHD/HD • IPS/TN • Original/OEM • 30min Service" },
    { id: 114, name: "Desktop RAM Upgrade", category: "Hardware Repair", price: 500, image: "images/service-hardware.png", desc: "All Brands • DDR3/DDR4 • Installation • Testing • Warranty" },
    { id: 115, name: "Laptop RAM Upgrade", category: "Hardware Repair", price: 500, image: "images/service-hardware.png", desc: "All Brands • DDR3/DDR4 • SODIMM • Installation • Testing" },
    { id: 116, name: "SSD/HDD Installation", category: "Hardware Repair", price: 500, image: "images/service-hardware.png", desc: "SSD/HDD Installation • OS Migration • Cloning • Data Transfer" },
    { id: 117, name: "Laptop Hinge Repair", category: "Hardware Repair", price: 1500, image: "images/service-hardware.png", desc: "Broken Hinge • Screen Support • All Brands • Quick Fix" },
    { id: 118, name: "Laptop DC Jack Repair", category: "Hardware Repair", price: 1200, image: "images/service-hardware.png", desc: "Charging Port • DC Jack Replacement • Soldering • All Brands" },
    { id: 119, name: "Server RAID Configuration", category: "Networking Setup", price: 3000, image: "images/service-network.png", desc: "RAID 0/1/5/10 • Configuration • Data Migration • Testing" },
    { id: 120, name: "Server OS Installation", category: "OS Installation", price: 3000, image: "images/service-os.png", desc: "Windows Server • Linux Server • Drivers • Configuration • RAID" }
  ]
};

// Cache-busting & LocalStorage sync
if(typeof window !== 'undefined') {
  const saved = localStorage.getItem('cctech_db_version');
  if(saved !== CCData.version) {
    localStorage.removeItem('cctech_db');
    localStorage.setItem('cctech_db_version', CCData.version);
  }
  if(localStorage.getItem('cctech_db')) {
    try {
      const local = JSON.parse(localStorage.getItem('cctech_db'));
      if(Array.isArray(local.products)) CCData.products = local.products;
      if(Array.isArray(local.services)) CCData.services = local.services;
    } catch(e) {}
  }
}
